### ISSUE TITLE
Please provide an HCI over UART example for BL651 and BL652

### ISSUE THREAD

**Issue by mmittek** [LairdCP/BL65x-Zephyr-Tutorials#1]
I am having very hard time trying to get the BL652 and BL651 to work using Zephyr's HCI example. Same code running on PCA100040 works flawlessly. The BL65X modules fail when asked to advertise.

**Comment by thedjnK** [comment]
Have you either set the LFRC source to internal RC, or connected the external 32KHz crystal as described in https://github.com/LairdCP/BL65x-Zephyr-Tutorials/blob/master/docs/HTSwith32kHzXtal.md ?
